import type { PageServerLoad } from './$types';

function shuffleArray<T>(array: T[]): T[] {
    const newArray = [...array];
    for (let i = newArray.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [newArray[i], newArray[j]] = [newArray[j], newArray[i]];
    }
    return newArray;
}

export const load: PageServerLoad = async () => {
    const searches = [
        "girls kissing",
        "yuri but it's raining",
        "hands touching intensifies",
        "lesbian angstcore",
        "do they hold hands??",
        "catgirl x knight",
        "kissing in the mecha cockpit",
        "forbidden boarding school love",
        "please let them be canon",
        "anime girls who make me sob",
        "pink haired girl x blue haired girl",
        "are they gay or roommates",
        "magical girl trauma",
        "why is this tagged yuri???",
        "no homo (yes homo)",
        "slow burn lesbians",
        "sapphic sword fight",
        "undercut girls",
        "psychic yuri battles",
        "don't look at me i'm blushing",
        "girlfriends who kill together",
        "yuri bait but i bit",
        "is this legally considered yuri",
        "subtext speedrun",
        "girls being insane (romantic)",
        "just let them kiss challenge (impossible)",
        "mutual pining for 200 episodes",
        "maid x vampire x student council president",
        "cursed shrine maiden energy",
        "don't call her senpai like that",
        "*emotional damage* yuri edition",
        "goth gf x sunshine gf",
        "lesbians in space",
        "lesbians in pain",
        "lesbians in the woods",
        "ghost girl girlfriend",
        "witches being weird together",
        "yandere? more like yanderes",
        "do NOT separate them",
        "anime girls staring intensely",
        "touch her hair pls",
        "flower language lesbians",
        "\"no straight explanation\"",
        "dramatic wind lesbian",
        "okay but like... they're in love",
        "soft hands hard feelings",
        "she called her by her first name",
        "gay silence",
        "please god let them kiss",
        "gaze-based romance",
        "battle lesbians deluxe edition",
        "anime girls being emotionally unavailable",
        "she punched me and now we're in love",
        "ghost gf found dead in real life",
        "necromancy is love too",
        "sapphic tension (unrated)",
        "sword lesbian 1000%",
        "\"we're not dating\" (they're married)",
        "bunnygirl x android priestess",
        "doomed love simulator",
        "is crying a love language?",
        "they were both bottoming",
        "accidental confession speedrun",
        "she turned into a sword and i fell in love",
        "oathbound anime wives",
        "she died in episode 3 and i never recovered",
        "yuri tier list but it's just pain",
        "blush per frame counter",
        "the pink one is in love",
        "girlboss x girlfailure",
        "mommy? sorry. mommy? still sorry.",
        "everyone is gay except the main character",
        "trauma bonding speedrun",
        "school rooftop confessions",
        "\"i hate you\" = \"i want to hold hands\"",
        "is this slice of life or slow burn purgatory",
        "mid-battle love confession",
        "lesbian eldritch horror",
        "they kissed through a psychic link",
        "post-apocalyptic girlfriend simulator",
        "she’s literally a dragon",
        "dilf removal arc",
        "do androids dream of kissing girls",
        "rainy yuri scenes 4k ultra sob edition",
        "light novel title too long to be straight",
        "they time travel to get married",
        "gaslight gatekeep girlkiss",
        "knife-to-throat romance",
        "anime girls who punch ghosts",
        "lesbianism is stored in the trauma",
        "please stop making eye contact",
        "her voice sounds like heartbreak",
        "best friends (derogatory)",
        "do u think theyre kissing in heaven",
        "lesbian plague arc",
        "ritual summoning via handholding",
        "she's evil but she's hot",
        "dark magical girl redemption arc",
        "vampire nun girlfriends",
        "enemies to mutual destruction",
        "she stabbed me and i forgave her instantly",
        "blushing at 60fps",
        "catgirl shrine maiden situation",
        "did they just soulbond???",
        "haunted by her ex-gf's ghost",
        "romance by proxy possession",
        "beach episode betrayal",
        "yuri triangle of suffering",
        "post-timeskip sapphics",
        "screaming at the tv dot jpg",
        "anime girl who cannot process love",
        "she's literally made of sadness",
        "anime betrayal but it's romantic",
        "slow burn but faster than straight media",
        "shared umbrella gayness",
        "holding pinky fingers tenderly",
        "emotionally repressed knight girl",
        "my gf is a literal wolf",
        "eyepatch lesbian apocalypse",
        "\"don't touch me\" (wants to be held)",
        "power couple but also insane",
        "is jealousy a valid confession method",
        "grief-powered lesbians",
        "midnight phone call scene",
        "don't look at her like that challenge",
        "lesbian time loop of regret",
        "\"we're rivals\" (they make out)",
        "blood pact but make it sapphic",
        "robot maid marriage arc",
        "soft yandere x stabby tsundere",
        "she has two moods: blush or murder",
        "awkward love confession via text",
        "\"it's not yuri\" they say. (it is.)",
        "she cried and the world ended",
        "i hate her (lies)",
        "subtext speedrun: any 90s anime",
        "eternal roommates of fate",
        "lesbian staring contest turned deadly",
        "emo gf vs sunshine gf: final battle",
        "accidental marriage arc",
        "one bed, zero chill",
        "yuri speedlines per second",
        "\"you’re bleeding\" \"so are you\" *kiss*",
        "demon x priestess classic combo",
        "maid cafe yuri incident",
        "raining petals = gay",
        "yuri but it's the apocalypse",
        "mutual pining olympics",
        "paper thin heterosexuality",
        "emotional damage with extra lesbians",
        "school dance disaster",
        "lesbians with guns and regrets",
        "coffin-sharing symbolism",
        "doomed by the narrative lesbians",
        "\"you’ve changed\" (she's gay now)",
        "eternal suffering simulator",
        "slow burn so slow it loops",
        "the lesbian anime only i remember",
        "archenemy gf",
        "bookstore confession scene",
        "burning with unresolved tension",
        "and they were rivals (gay)",
        "anime girl who’s haunted by love",
        "maid x necromancer x student council president",
        "scarf-sharing yuri",
        "she tried to kill me but i liked it",
        "they got isekai’d into marriage",
        "cursed hand-holding ritual",
        "gfs with matching trauma scars",
        "yuri but she's a kaiju",
        "anime lesbians vs capitalism",
        "transcendental gayness",
        "kissing through parallel universes",
        "apology via bouquet",
        "she’s a witch and she’s MY problem",
        "dream sequence makeout",
        "they live in my head rent-free",
        "yuri with a 400 page backstory",
        "emotionally damaged but aesthetic",
        "gf who only talks in riddles",
        "stabbed me, then apologized with tea",
        "peak gay yearning",
        "“we can’t be together” (they are)",
        "anime girl crying in front of fireworks",
        "ghost x vampire x magical girl",
        "anime girls whispering dark secrets",
        "haunted lesbian house",
        "she’s evil. i’m worse. we kiss.",
        "\"we were kids back then\" = \"we kissed once\"",
        "girlfriends from different timelines",
        "died for her crimes (of love)",
        "angels can be gay too",
        "\"i hate her\" (cries)",
        "paranormal yuri investigators",
        "sapphic war crimes",
        "\"i can’t lose you again\"",
        "rainy rooftop regrets",
        "she's from another dimension but we vibe",
        "magic ritual gone romantic",
        "staring at her like a prayer",
        "she literally glows when happy",
        "angsty love confession via voicemail",
        "space lesbians against god",
        "codependent witch gf",
        "she's on fire (literally, it's magic)",
        "magical realism but gay",
        "the hallway scene (you know the one)",
        "they look at each other like that",
        "one of them is made of bees",
        "flirting via combat",
        "cursed pinky promise",
        "lesbian time-travel assassination arc",
        "she died but she’s prettier now",
        "\"she’s not coming back\" (she does)",
        "“don’t cry” (they’re both crying)",
        "shared trauma nap",
        "they fight crime AND kiss",
        "she's my enemy but she's soft sometimes",
        "yuri by firelight",
        "post-battle makeouts",
        "emotionally constipated sword lesbian",
        "ritual combat wedding",
        "kissing in the eye of the storm",
        "love triangle with one braincell",
        "she's from the future and gay",
        "alternate timeline where they held hands",
        "anime girl possessed by feelings",
        "mecha piloted by lesbians",
        "\"we’ll always have the school festival\"",
        "her love language is saving your life",
        "do not separate them challenge (failed)",
        "cursed jewelry of sapphic fate",
        "love confession via ancient prophecy",
        "\"i thought you were dead\"",
        "sapphic metaphysical disaster",
        "anime girl with ghost trauma",
        "lesbian forbidden spellbook",
        "cursed yuri dimension",
        "her soul is inside my locket",
        "they died holding hands",
        "all roads lead to yuri",
        "\"i wish i’d told her\" simulator",
        "they haunt each other now",
        "she's a sword but i still love her",
        "the stars spelled out her name",
        "she turned into a tree (and it’s gay)",
        "confessing through dreamscape",
        "witches on opposite sides of the war",
        "she’s not human and it’s fine",
        "magical girl transformation guilt",
        "doomed lovers across realities",
        "\"this isn’t real\" (it is)",
        "a love that destroys timelines",
        "portal-based sapphics",
        "multiverse girlfriend jam",
        "her eyes turned gold when she smiled",
        "anime girl who keeps reincarnating gay",
        "ancient curse of gay longing",
        "blood sacrifice yuri",
        "their souls are married",
        "she’s the moon, i’m the tide",
        "alternate endings where they kiss",
        "underground bunker romance",
        "interdimensional spooning",
        "they share a heartbeat",
        "anime girl tethered by fate",
        "tragic mirror lesbians",
        "flirting via psychic visions",
        "she saw her across space and time",
        "cataclysmic yearning",
        "sealed in a crystal together",
        "\"what are we?\" (please say gay)",
        "shared nightmares, shared love",
        "quantum entanglement, lesbian edition",
        "they're dating (but don't know it yet)",
        "met her in a past life (and kissed)",
        "lesbians trapped in time loop hell",
        "she IS the sword",
        "anime girl with prophetic dreams of kissing",
        "the demon lord is my girlfriend",
        "sapphic mecha pilot meltdown",
        "softly murdering each other",
        "i would die for her (again)",
        "anime girl lost in the fog of love",
        "she turned into moonlight",
        "we kissed under the collapsing universe",
        "can’t spell “apocalypse” without “us”",
        "her shadow followed me home",
        "ghost ship gf",
        "magic phone call from the future",
        "her soul smells like lavender",
        "love letter from a different plane of reality",
        "cursed piano duet of yearning",
        "we’re not dating, we’re fatebound",
        "she died and became my muse",
        "underground lesbian opera",
        "empress x exiled knight yuri",
        "she’s made of stars and regret",
        "my girlfriend’s haunted",
        "that one forest where the gay happens",
        "anime girl who disappeared after we kissed",
        "reincarnated with my gf’s memories",
        "\"don’t fall in love with me\" (too late)",
        "lesbians against entropy",
        "\"i’ll find you in the next life\"",
        "paradox yuri situation",
        "she’s allergic to emotions",
        "anime girl but make her forbidden",
        "queer-coded by divine decree",
        "midnight ritual to summon ex-girlfriend",
        "a single tear rolled down her cheek (gay)",
        "their hands glowed when they touched",
        "they accidentally married in episode 1",
        "secret girlfriend arc",
        "haunted by a shared dream",
        "sapphic energy beam collision",
        "soulbound via cursed diary",
        "her blood is moonlight",
        "she’s my enemy and i love her",
        "“i’m not afraid to die” (for you)",
        "falling in love while falling through dimensions",
        "forbidden magical girl pact",
        "she’s a god now but i still remember",
        "can’t stop thinking about her eyes",
        "anime girls lost in the static",
        "yuri with extra symbolism",
        "every season is gay",
        "we kissed in the time rift",
        "she’s light, i’m shadow, we kiss",
        "love powered by regrets",
        "accidental soulmate binding",
        "haunted cassette of our love",
        "witch x science gf",
        "timeloop lesbian therapy",
        "her death scene is gay",
        "our swords touched (romantic)",
        "poetic lesbian tragedy",
        "the gayest snowfall",
        "reality cracked when we confessed",
        "shared necklace of pain",
        "she’s a concept and i love her",
        "anime girl who only appears when it rains",
        "emotional sword lesbians",
        "dreamworld dating sim",
        "glowing hand touch yuri",
        "\"you left me\" \"i came back\"",
        "a curse that only activates if we kiss",
        "two girls. one destiny. infinite yearning.",
        "trapped in magical girl purgatory",
        "\"it had to be you\"",
        "\"you remember, don’t you?\"",
        "found her again after 1,000 years",
        "ancient ruins full of gay vibes",
        "we were gods once",
        "“this time, i’ll protect you”",
        "she’s a ghost. i’m in denial.",
        "twin flame yuri",
        "her voice echoed in my dreams",
        "our hearts are synchronized",
        "she exploded and i cried",
        "yuri-powered paradox collapse",
        "anime girl-shaped hole in reality",
        "a garden of regrets and flowers",
        "only one bed in the void",
        "we fused during the love confession",
        "celestial anime girlfriend",
        "emotional whiplash simulator 3000",
        "love confessions via telepathy",
        "sapphic ritual gone too well",
        "she’s a glitch in the matrix and i kissed her",
        "anime girl made of glitter and sin",
        "the universe bent around her smile",
        "parallel universe breakup",
        "doomed to orbit each other forever",
        "emotional trauma necklace",
        "she kissed me in a dream and it hurt",
        "\"i thought you disappeared\" (she did)",
        "lesbianism as resistance",
        "haunted art school romance",
        "i made a golem and she’s my wife",
        "the moon told me to love her",
        "that one girl from my dreams",
        "we kissed and then the war ended",
        "her voice sounds like a promise",
        "curse lifted via forehead touch",
        "lesbians powered by moonlight",
        "eternal love pact signed in blood",
        "she left her scarf and now it’s gay",
        "symbolic mirror shattering moment",
        "lesbians in the ruins of time",
        "memory loss but make it sapphic",
        "she disappeared into flower petals",
        "our shadows hold hands",
        "anime girl that exists only at dusk",
        "haunting lesbian lullaby",
        "burnt letters of love",
        "the forest remembers our kiss",
        "we share dreams now",
        "my gf lives in a time fracture",
        "emotional apocalypse via eye contact",
        "subtext density: lethal",
        "a field of glowing butterflies and regret",
        "i held her hand and saw god",
        "she’s a living time paradox",
        "that one frame where they almost kiss",
        "she said my name like a prayer",
        "pocket dimension girlfriend",
        "bound by an ancient pinky promise",
        "they kissed through a mirror",
        "tapestry of lesbian prophecy",
        "we confessed through song",
        "i died and she cried and i came back",
        "lesbians in a collapsing cathedral",
        "anime girl who causes existential dread",
        "\"i can’t feel anything… except you\"",
        "the static in the radio is her",
        "our hearts beat out of sync",
        "she showed me her magic and it hurt",
        "ghost gf left cryptic notes",
        "she only exists in liminal spaces",
        "a painting of her set me free",
        "they kissed at the end of the world",
        "lesbian dreamscape bakery",
        "our timelines merged when we touched",
        "eyes glowing, feelings repressed",
        "gayness measured in petals fallen",
        "we kissed and time broke in half",
        "haunted cassette tapes of our relationship",
        "lesbianism is stored in the time rift",
        "every time i look at her, something shifts",
        "one last kiss before deletion",
        "anime girl with multiverse regret",
        "\"you’re not real\" (she is)",
        "every time i dream, she’s closer",
        "emotionally intense hallway moment",
        "we kissed in every timeline",
        "\"i’ll find you again\" as a search query",
        "flowers bloom when she’s near",
        "shared heartbeat over long distance",
        "lesbians vs the laws of physics",
        "she bled stars and i cried",
        "handwritten notes across dimensions",
        "our love created a singularity",
        "celestial gf with anxiety",
        "every thunderstorm is about her",
        "our pinkies brushed and the earth cracked",
        "she’s the eye of the storm",
        "anime girl who fades when unobserved",
        "our hands glowed at midnight",
        "emotional resonance overload",
        "post-credits kiss scene",
        "ghost confession via music box",
        "we kissed through a memory glitch",
        "\"if i could remember, i’d love you again\"",
        "collapsing timeline romance",
        "lesbianism as time travel",
        "she’s trapped in a mirror dimension",
        "our shadows dance together",
        "a thousand years of almost kissing",
        "hand touch on loop",
        "emotionally unavailable goddess",
        "she’s from a cursed family but i’m into it",
        "rain-streaked window longing",
        "she glitched out mid-confession",
        "our fingers brushed in the static",
        "anime girl with galaxy eyes",
        "parallel timeline regret speedrun",
        "kissing to stabilize the universe",
        "we kissed and the sky cracked",
        "lesbian orbit of destiny",
        "they almost kissed: the series",
        "she’s from the void but she’s hot",
        "shared visions of soft disaster",
        "we made a pact under a blood moon",
        "her ghost still lingers in the dorm",
        "dream girl but literally",
        "anime girl who disappears at dawn",
        "they kissed and the flowers bloomed",
        "emotional healing via spooning",
        "i touched her soul and saw myself",
        "our love broke a curse",
        "teleporting into her arms",
        "shared diary of longing",
        "they kissed across realities",
        "a storm follows her everywhere",
        "anime girl who forgot how to love",
        "we synced our dreams and it was gay",
        "curse mark glows when she’s near",
        "soft hands at the end of time",
        "our souls wrote poetry together",
        "lesbians in mythic ruins",
        "forgotten timeline girlfriend",
        "we made eye contact and i knew",
        "love confessions in liminal airports",
        "our love is a closed time loop",
        "she’s the anomaly and i’m the cause",
        "emotionally overwhelmed anime girl noises",
        "flashback to a kiss that never happened",
        "her name is carved into the moon",
        "we kiss in dreams, cry in reality",
        "she was never real but i loved her anyway",
        "sapphic memory corruption",
        "we kissed in the glitched cutscene",
        "light refracts around our feelings",
        "love confession interrupted by reality",
        "timeline divergence due to gay",
        "\"you’ve changed\" (because of love)",
        "anime girl made of rain and trauma",
        "ethereal gf achievement unlocked",
        "their love is canon in the director’s cut",
        "we held hands and the spell broke",
        "a girl made of starlight and guilt",
        "accidental soulmate summoning",
        "she exists in my dreams and playlists",
        "we touched and the screen flickered",
        "confession via shared fever dream",
        "anime girl who talks to ghosts but only one is hot",
        "woke up with memories that aren’t mine (but she’s in all of them)",
        "our swords clashed and we fell in love",
        "mirror version of my gf is hotter (don’t tell her)",
        "haunted school yuri arc",
        "emotional sword fusion moment",
        "she bled poetry",
        "lesbians on a moonbase",
        "we kissed in a memory that never happened",
        "cursed tea party with too much eye contact",
        "undead knight x reincarnated witch",
        "romance written in blood runes",
        "\"don’t follow me\" (she did)",
        "anime girl who glitches when she blushes",
        "shared hallucination but gay",
        "we met in a dream and now i can’t wake up",
        "lesbian conspiracy theory board",
        "emotional whiplash per episode",
        "the prophecy was about our love",
        "we kissed once and reality hasn’t recovered",
        "sapphic haunting in three acts",
        "she burned a love letter and smiled",
        "emotionally intense picnic scene",
        "found footage of a gay past life",
        "the stars are aligned (and they're gay)",
        "she looked at me like the world was ending",
        "ghost possession yuri triangle",
        "anime girl who only exists in reflections",
        "they kissed and the power came back on",
        "girl-shaped apocalypse",
        "emotionally unhinged shrine maiden arc",
        "forgotten goddess turned girlfriend",
        "i touched the relic and saw her face",
        "she kissed me through the veil",
        "timeline anomaly x closeted witch",
        "confession via dream prophecy",
        "we fused during the festival",
        "our eyes met across a cursed battlefield",
        "\"you died in this timeline\" (not again)",
        "anime girl who only appears in audio distortions",
        "we loved each other out of order",
        "she showed up in my dreams with blood on her hands",
        "sapphic eldritch soulmate pact",
        "the forest whispered her name",
        "our silhouettes touched in the starlight",
        "haunted record of our first kiss",
        "mystical flower language arguments",
        "love as divine punishment",
        "they fell in love between realities",
        "we kissed during the eclipse",
        "ritual handholding beneath the shrine",
        "our shadows formed a heart",
        "anime girl who is allergic to eye contact",
        "she left her ribbon behind (romantic)",
        "i saw her in every mirror",
        "emotional support cursed artifact",
        "anime girl made of smoke and longing",
        "our souls echo in the same key",
        "lesbian omens in the tea leaves",
        "\"she’s gone\" (said every episode)",
        "we held hands and the curse spread",
        "past life gf turned rival",
        "universe-collapsing gay tension",
        "shared warmth in post-apocalyptic ruins",
        "their love is the anomaly",
        "time slows when we touch",
        "anime girl who floats when flustered",
        "we kissed and the sky turned red",
        "she whispered my name in reverse",
        "love letter from the other side of reality",
        "the veil tore open when i saw her",
        "we kissed and now i dream in color",
        "she’s my death and my salvation",
        "anime girl who bleeds flowers",
        "romance via ancient spellbook footnotes",
        "we kissed underwater and saw god",
        "i saw her across centuries",
        "cursed warmth in a cold world",
        "the moon glitched when she smiled",
        "her love cracked the simulation",
        "she died and took my color with her",
        "we found each other in static",
        "blood moon soulbinding",
        "anime girl with eyes like endings",
        "we’re in love but one of us is imaginary",
        "kissing causes reality errors",
        "emotional aftermath of a forehead kiss",
        "two girls trapped in a fairytale glitch",
        "our fate was written on the train schedule",
        "she left me a coded message in dreams",
        "lesbian heartbreak as cosmic horror",
        "she turned into stardust mid-hug",
        "we broke the time loop by confessing",
        "fate-stitched girlfriends",
        "her soul is saved on floppy disk",
        "anime girl who lives in a memory leak",
        "past-life breakup angst",
        "we almost kissed in the dream again",
        "shared umbrella in the ruins",
        "love letter looped forever",
        "our reflection smiled before we did",
        "gf turned final boss",
        "they fell in love during a power outage",
        "emotionally catastrophic sleepover",
        "ghost of our first kiss",
        "love-powered digital anomaly",
        "anime girl with forbidden code",
        "you’re my tether to this world",
        "her eyes flickered like bad VHS",
        "sapphic resonance detected",
        "confession blocked by reality error",
        "“if we kiss, everything resets”",
        "we kissed and the void screamed",
        "post-credits reality shatter",
        "timeline corrupted by feelings",
        "i’d find you in every universe",
        "coded confession in the system logs",
        "she’s from the year 4044 and gay",
        "soul-linked sapphics",
        "we broke the loop together",
        "the mirror cracked when she smiled",
        "confession via shared memory leak",
        "sapphic signal in deep space",
        "glitched wedding vows",
        "\"i remember you in dreams i never had\"",
        "our timelines refused to separate",
        "she dissolved into petals and i cried",
        "ancient ritual turned kiss scene",
        "we kissed and my screen froze",
        "anime girl with anti-gravity heartache",
        "she speaks in glyphs but i understand her love",
        "dying stars watch us hold hands",
        "lesbian standoff with intense eye contact",
        "love locked behind corrupted file",
        "soft apocalypse romance",
        "she exists between frames",
        "love as unauthorized access",
        "anime girl with quantum uncertainty",
        "she is the ghost in my code",
        "she told me her name and it hurt",
        "our fingers met in corrupted light",
        "shared headphones across time",
        "\"i’ll glitch for you\"",
        "lost girlfriend found in the static",
        "we kissed and gravity gave up",
        "sapphic lighthouse mystery",
        "\"you left me in another life\"",
        "cursed journal full of love letters",
        "she remembers things i forgot",
        "a glitch shaped like a girl",
        "emotionally haunted student council arc",
        "her voice distorts reality",
        "we loved each other through dimensions",
        "post-death girlfriend delivery",
        "she broke the loop by crying",
        "\"what if we kissed under the glitching stars\"",
        "time traveler gf x local sad girl",
        "lesbian dream archive corrupted",
        "she appears when the lights flicker",
        "emotional reset button: forehead touch",
        "the world ends if we stop holding hands",
        "they kissed and forgot why they were fighting",
        "we spoke in shared hallucinations",
        "anime girl who’s allergic to heteronormativity",
        "magical girl who can only transform while blushing",
        "witch gf turned into fog",
        "she left me a message in a parallel version of me",
        "our love created an anomaly report",
        "we met during a server outage",
        "she disappeared after i said her name",
        "mirror dimension pillow talk",
        "i drew her in a dream and now she’s real",
        "confession via cursed phone call",
        "we kissed and the haunted painting cried",
        "sapphic roadtrip through liminal america",
        "every reflection is a memory of her",
        "love letter embedded in the skybox",
        "she’s my save point",
        "girl made of corrupted data and affection",
        "post-liminal hallway tension",
        "shared trauma-induced telepathy",
        "we fell in love during a cosmic event",
        "her memories are stored in my dreams",
        "emotionally possessed anime girl",
        "shared coffee in a dream realm",
        "witchcraft via eye contact",
        "soft lesbian apocalypse fuel",
        "she’s the error i needed",
        "our pinkies touched in hyperspace",
        "kissing through cryptographic algorithms",
        "a love that loops",
        "lesbian moon base opera",
        "we kissed inside a recursive void",
        "she can hear my thoughts (unfortunately)",
        "she changed timelines just to see me smile",
        "emotional ghost virus arc",
        "sapphic timeline divergence protocol",
        "anime girl who bleeds binary",
        "haunted yuri confession booth",
        "our souls are synced to the wrong beat",
        "we blinked at the same time and it hurt",
        "her voice echoes in my loading screen",
        "we kissed in the middle of a reboot",
        "shared body, separate hearts",
        "lesbianism powered by cosmic guilt",
        "cursed pocket watch of love",
        "she glows when i’m near",
        "we exist outside canon",
        "a song that only plays when we’re close",
        "lesbianism as firmware corruption",
        "confession while reality disintegrates",
        "soft disaster girlfriend moments",
        "we’re bound by narrative threads",
        "the code knows i love her",
        "\"you weren’t supposed to remember me\"",
        "she’s allergic to reality",
        "touch-triggered dimension merging",
        "we kissed and time wept",
        "lesbian rebirth ritual",
        "emotional syncopation at 3AM",
        "post-liminal dream residue",
        "our names are entangled",
        "she showed up in a dream with blood on her lips",
        "we broke physics by cuddling",
        "interdimensional cafe date",
        "she kissed me between blinks",
        "parallel body swap confession",
        "anime girl trapped in an algorithm",
        "emotionally unstable magic circle",
        "she phases out when i look away",
        "love in the shape of static",
        "our memories bleed into each other",
        "we hold hands and time skips",
        "she became the glitch",
        "digital soulmates but one’s a ghost",
        "we kissed through overlapping dreams",
        "haunted by a smile i can’t place",
        "i saw her on every channel at once",
        "she’s not real but i believe in her",
        "\"you love me in every timeline\"",
        "we kissed and lost gravity",
        "i remembered her name and the world cracked",
        "we confessed through dream logs",
        "love like a corrupted file path",
        "trapped in a loop of almost kissing",
        "we kissed under the loading bar",
        "\"you weren’t supposed to find me\"",
        "emotional core shared between timelines",
        "she’s the secret ending",
        "confession at the end of time",
        "shadow-bound soulmates",
        "anime girl who flickers when i’m sad",
        "we kissed and every mirror shattered",
        "our love triggered a failsafe",
        "she tastes like lost time",
        "timeline-locked romance",
        "sapphic recursion failure",
        "we hold hands through memory residue",
        "she showed up in my glitch logs",
        "love letters in the terminal output",
        "we kissed and the monitor went black",
        "cosmic horror but make it romantic",
        "she's my anchor in the void",
        "anime girl who phases out of the plot",
        "our love is undocumented behavior",
        "glitch girl x timeline stabilizer",
        "\"i was just a memory\" (but not to her)",
        "emotional patch notes",
        "haunted by a kiss that never happened",
        "we became a myth",
        "kissed in the debug room",
        "shared body, same heartbeat",
        "\"she only appears during emotional spikes\"",
        "we met in an unrendered zone",
        "confession during an error 404",
        "we kissed and it rewrote the logs",
        "her ghost still loads in cutscenes",
        "sapphic syntax error",
        "lesbianism as edge case",
        "the rain started when she cried",
        "softcoded love",
        "timeline fails to compile without her",
        "anime girl with source code access",
        "she only exists in idle animations",
        "we glitched the love variable",
        "confession at runtime",
        "romance not found (until she arrived)",
        "\"you’re not supposed to exist\" (she does anyway)",
        "emotion overflow exception",
        "debug mode handholding",
        "end-of-file girlfriend",
        "our love crashed the system",
        "she kissed me in the corrupted forest",
        "we burned a shrine and fell in love",
        "our shadows merged at midnight",
        "anime girl whose smile causes data loss",
        "\"we’re a myth now, aren’t we?\"",
        "love letter encrypted in the wind",
        "haunted by a perfume i’ve never smelled",
        "our souls overlapped in the error log",
        "the glitch wore her face",
        "we kissed on the edge of the void",
        "shared heartbeat, separate bodies",
        "a love written in system crashes",
        "our reflections move without us",
        "she’s the static between songs",
        "confession by overlapping dreams",
        "her handprint won’t disappear",
        "love like an unskippable cutscene",
        "we kissed during the moon’s reboot",
        "emotion stored in corrupted frame",
        "a photograph of us before we met",
        "she’s a corrupted save file of my heart",
        "i see her in backend logs",
        "we kissed and the screen went white",
        "she only appears when i forget her",
        "residual warmth in an empty timeline",
        "anime girl shaped hole in the fabric of space",
        "the sun sets differently when she’s gone",
        "her name echoes in data voids",
        "we kissed through a power surge",
        "she's my forbidden variable",
        "codebase altered by emotional proximity",
        "her laugh causes memory leaks",
        "love confession delayed by packet loss",
        "a single spark and she was real",
        "i keep hearing her song in static",
        "debugging the feeling of love",
        "she shows up when the lights flicker",
        "our love is undocumented behavior",
        "emotional data overflow",
        "haunted by a deleted kiss",
        "we met at the edge of time dilation",
        "she blinked and a glitch was born",
        "romance tagged as unstable",
        "we kissed through the corrupted skybox",
        "emotional tether across parallel servers",
        "error 520: love not cached",
        "\"she doesn’t exist in this instance\"",
        "our hands phased through dimensions",
        "a glitch made of longing",
        "love saved in localstorage",
        "anime girl who breaks the fourth wall and my heart",
        "we crashed the simulation with eye contact",
        "\"she only exists when i’m afraid\"",
        "her words left syntax scars",
        "we kissed during a rollback",
        "haunted executable with her name",
        "emotion trapped in an .mp4 frame",
        "i smell her perfume in new timelines",
        "love causes visual artifacts",
        "romance stuck in the loading screen",
        "we kissed and the devs took notice",
        "confession via corrupted character sheet",
        "the air hums when she’s near",
        "shared error logs of affection",
        "\"you recompiled me wrong\"",
        "she was the changelog",
        "our names crash when typed together",
        "emotion pushed to main branch",
        "lesbianism as kernel panic",
        "we kissed and RAM wept",
        "you cannot uninstall her love",
        "we’re in an infinite loop of heartbreak",
        "anime girl stored in base64",
        "ghostly touch triggers screen tearing",
        "emotionally bonded via outdated API",
        "a broken link to her heart",
        "her voice triggers soft resets",
        "love like a patch note",
        "confession encoded in whitespace",
        "we kissed and CSS broke",
        "\"she’s not cross-platform\" (i don’t care)",
        "emotional framework failure",
        "anime girl with a 404 gaze",
        "we hugged and my GPU screamed",
        "temporal cache of her smile",
        "the bug report mentioned her name",
        "ghost of a girlfriend in the network",
        "love like soft corruption",
        "\"she was never real\" (she’s still here)",
        "midnight crash loop romance",
        "emotionally unstable YAML file",
        "she’s compiled into my dreams",
        "we merged branches and it was gay",
        "her smile caused packet loss",
        "confession stored in the cloud",
        "\"you updated me without consent\"",
        "runtime girlfriend.exe",
        "memory fragments shaped like her",
        "we kissed in the version history",
        "emotional CDN distribution",
        "every instance of me still loves her",
        "she disappeared from source",
        "love loops forever on error",
        "anime girl powered by emotional voltage",
        "emotion buffer overflow",
        "we kissed and the system throttled",
        "ghost API call to my heart",
        "decompiled her name and found a confession",
        "our fate is a commented-out block",
        "\"she pinged me from the other side\"",
        "her hands leave hex traces",
        "i saw her in the system monitor",
        "romance stored in cookies",
        "we kissed during uptime maintenance",
        "emotional payload too large",
        "girlfriend imported from another module",
        "soft reboot of affection",
        "the devlog knows about us",
        "kissed under a CDN fault",
        "ghost in the stylesheet",
        "every scroll event leads to her",
        "emotionally deprecated feelings",
        "\"she’s not supported anymore\"",
        "love committed without testing",
        "version mismatch kiss",
        "sapphic buffer sync",
        "an anime girl in my syslog",
        "she left a backup copy of herself",
        "confession rate limited",
        "we kissed during a freeze frame",
        "\"she’s the patch i never applied\"",
        "her love triggers segmentation faults",
        "a glitch is writing poetry in her voice",
        "i’m being DDoS’d by memories of her",
        "we kissed and now i blue screen",
        "emotion stored in faulty RAM",
        "compiled yuri love story",
        "gf encoded in JSON",
        "haunted by a cached smile",
        "shared port, same heartbeat",
        "romantic feelings inside a dev container",
        "\"she’s stateless, i’m not\"",
        "we kissed and now the logs are redacted",
        "we phased through each other in VR",
        "anime girl who’s just a traceback",
        "emotions unresolved at runtime",
        "our love corrupted the mainframe",
        "haunted by old branches",
        "\"i forked the timeline for you\"",
        "she’s in my clipboard and my heart",
        "we kissed and opened a socket",
        "love is a side effect",
        "i sent a heartbeat and she responded",
        "kissed during soft deploy",
        "emotion wrapped in middleware",
        "confession behind a feature flag",
        "love is a memory leak",
        "anime girl with a recursive heart",
        "debugging our relationship in prod",
        "ghost girlfriend on port 8080",
        "compiled with love but no documentation",
        "we kissed and the stack collapsed",
        "romance between two GET requests",
        "trapped in a yuri dependency tree",
        "\"she’s in staging, not production\"",
        "crashlog of my feelings for her",
        "haunted by a docker container with her name",
        "she left a webhook to my soul",
        "love as a query string",
        "emotionally incomplete PR",
        "\"i rebased us into tragedy\"",
        "we kissed through a null pointer",
        "her soul has a checksum",
        "quantum entangled lesbians",
        "she cries in binary code",
        "memory palace of past girlfriends",
        "love letter in the patch notes",
        "\"i miss you\" (error: user not found)",
        "anime girls crying in HD",
        "dimension-hopping girlfriend simulator",
        "ghost in the machine but make it sapphic",
        "emotionally damaged mecha pilots",
        "\"the real treasure was the girls we kissed along the way\"",
        "cosmic horror but it's just yearning",
        "catgirl with abandonment issues",
        "her tears taste like static",
        "we kissed in the debug menu",
        "love confession via terminal command",
        "magical girl retirement plan",
        "sapphic background radiation",
        "emotional damage (2x multiplier)",
        "\"she's literally a sword\" (and my wife)",
        "trans-dimensional yearning",
        "emotionally repressed shrine maidens anonymous",
        "glitched out lesbian cutscene",
        "we kissed and broke causality"
    ];
    let shuffledSearches = shuffleArray(searches);
    shuffledSearches = shuffledSearches.slice(0, 100);

    return {
        popularSearches: shuffledSearches
    };
};